### ISSUE TITLE
localhost: Not a Certification Authority

### ISSUE THREAD

**Issue by mondalaci** [jsha/minica#1]
I was able to execute `minica --domains localhost` successfully, then my web server could successfully use the generated files. Then I exported the root CA of the generated cert in Chrome, and upon trying to import it, I got the following error:

    localhost: Not a Certification Authority

Any ideas about this?

**Comment by cpu** [comment]
@mondalaci How did you export the root CA from Chrome? It sounds like you perhaps exported the leaf end-entity certificate.

**Comment by mondalaci** [comment]
@cpu That may have been a case. I didn't even notice that selecting a leaf actually affects the export. Now I know better. In any case, I've eventually managed to generate a self-signed certificate that works. Sorry for the noise, and thank you for your help!

**Comment by cpu** [comment]
@mondalaci Happy to hear you found your way to a working setup :tada: Thanks for following up and closing the issue :-)
