### ISSUE TITLE
Browser doesn't trust issuer

### ISSUE THREAD

**Issue by jms1989** [jsha/minica#10]
I think I did this right but Chrome says the cert is OK and Firefox won't trust it.

Chrome error
`NET::ERR_CERT_AUTHORITY_INVALID`

Firefox error
`Error code: SEC_ERROR_UNKNOWN_ISSUER`

Domain cert and root cert combied
`cat domain/cert.pem minica.pem >> domain/cert.crt`

NGINX CONFIG
`    ssl_certificate /path/to/certs/domain/cert.crt;`
`    ssl_certificate_key /path/to/certs/domains/key.pem;`

I'm not sure how to resolve this. I've imported the root CA into my computer's cert store.

EDIT: I guess I still have to add the domain cert to my computer's cert store for it to work. Well, it works but firefox still considers it insecure and chrome seems ok with it.  :/

**Comment by hyperpress** [comment]
Did you try a

**Comment by jms1989** [comment]
hmm, as much as I hate the idea of restarting chrome. it seems to work but firefox doesn't even see the cert. still giving "unknown issurer". chrome uses the system cert store. that window in chrome shows the same thing as the windows cert manager snap-in.

**Comment by hyperpress** [comment]
So, I just did the same thing in Firefox: Imported into Authority. (I didn't have to restart it) and it picked up my project SSL cert as trusted on the next project level page reload. I'm running Firefox 61.0.1, not that that should matter much. So, not sure what your issue might be caused by.

**Comment by jsha** [comment]
You may also be interested in [`mkcert`](https://github.com/FiloSottile/mkcert), which tries to automate the process of adding your newly minted root to the local trust store.
