### ISSUE TITLE
Not trusted by the browsers?

### ISSUE THREAD

**Issue by luiz-brandao-jr** [jsha/minica#25]
I'm trying to setup certificates for some local servers I have in a VM. I added the root certificate to my Trusted Root Certification Authorities / Certificates in my host machine (Windows) but even after that, browsers keep marking the local website as risky and not trustworthy. 

Firefox gave me this error "SEC_ERROR_UNKNOWN_ISSUER", "Peer’s Certificate issuer is not recognized.". Do you know a way to get around that?

Thank you, and thanks for this.

**Comment by luiz-brandao-jr** [comment]
Oops, seems like a duplicate of #10

**Comment by jsha** [comment]
For Firefox, you need to separately add the root to Firefox's own root
store, under preferences.

**Comment by hyperpress** [comment]
Yes, I had to import mine into Firefox and restart. It works fine in Chrome
and FF for me.
