### ISSUE TITLE
decrease length of cert to max 825-day

### ISSUE THREAD

**Issue by oppianmatt** [jsha/minica#32]
https://derflounder.wordpress.com/2019/06/06/new-tls-security-requirements-for-ios-13-and-macos-catalina-10-15/

Due to recent mac update, minica certs are now no longer working due to being too long

and no option but to edit source

**Comment by Shikkic** [comment]
Yeah we're running into the same issue 😞

**Comment by jsha** [comment]
Thanks for the report! Pushed a fix, please let me know if you have any problems with it.

**Comment by Shikkic** [comment]
Thanks for pushing that out @jsha we'll give it a go and see how it works!

**Comment by kaylesworth** [comment]
@jsha We tested this today but it set the cert to 4/11/2024, 1644 days instead of the 825

**Comment by jsha** [comment]
I made a mistake in my previous change. @Nicolas-Duboc-IBM helpfully fixed it in #35. Please try again and report back!
