### ISSUE TITLE
Google Chrome complains NET::ERR_CERT_VALIDITY_TOO_LONG

### ISSUE THREAD

**Issue by mistakster** [jsha/minica#39]
There is a limit for the certificate expire date. The validity duration shouldn't be more than 825 days.

@jsha, is it possible to reduce the duration of the generated certificates, please?

**Comment by kmpoppe** [comment]
When I just generated a certificate without any additional options, the validity was set to 2 years 1 month by default.
Not much more I can help to enlighten you, I fear.
Kai

**Comment by mistakster** [comment]
@kmpoppe, thanks for your time. It seems I used an outdated version. I tried to generated certificates with the latest one, and Chrome accepts it without issues.
