### ISSUE TITLE
Open Source license?

### ISSUE THREAD

**Issue by tbehling** [jsha/minica#6]
Hi there @jsha, I learned about this project while reading [docs for Let's Encrypt](https://letsencrypt.org/docs/certificates-for-localhost/).  It's a very cool looking project and I'm impressed you were able to do it in one Go file with no dependencies (it's a real testament to the Go standard library too).

I opened this issue because I was interested in taking a crack at a couple of the ideas from the open issues, as a pull request if you're open to it.  I didn't see a license in this repo, which is understandable for a small project like this, but would you be open to adding one?  GitHub has a nice web site at https://choosealicense.com/ to find one that makes sense for you.

(Disclaimer, I am a GitHubber but this is just out of personal interest and not any kind of official communication from GitHub)

**Comment by jsha** [comment]
Hi! Thanks for the interest. I'd be happy to add a license; want to submit a PR for the MIT license?

**Comment by tbehling** [comment]
Hi there, thanks for the fast response!  It looks like #7 has beaten me to the punch here and makes the same addition I would have done.

**Comment by actualben** [comment]
@tbehling - Looks like I didn't get the "Closes #6" note put in the description in time.
