### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [jsha/minica#69]
👋 looks like 1.1.0 release was not completed, ie the release notes did not get created. Create this issue to raise some awareness. Thanks!

cc @aarongable

relates to https://github.com/Homebrew/homebrew-core/pull/171334

**Comment by chenrui333** [comment]
cc @aarongable

**Comment by jsha** [comment]
Fixed! Thanks for the note. https://github.com/jsha/minica/releases/tag/v1.1.0

**Comment by chenrui333** [comment]
Thanks! Close via https://github.com/Homebrew/homebrew-core/pull/171334
