### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by ankane** [jsha/minica#9]
Hey, thanks for this great project 👍 It's super easy to use - just updated one of my [tutorials](https://medium.com/@ankane/securing-database-traffic-with-pgbouncer-and-amazon-rds-c775b10bad75) to use it.

Is it possible to tag releases on Github? I'd like to create a Homebrew formula for it.

**Comment by jsha** [comment]
Thanks for the suggestion! I just tagged v1.0.0.

**Comment by ankane** [comment]
Thanks @jsha, submitted a PR to Homebrew. https://github.com/Homebrew/homebrew-core/pull/33055
